### PR TITLE
[Fix #15 #3] Allow to specify the config file location & stop on failure

### LINKED ISSUE #15: Allow to specify the config file location
For example, in Laravel 5, it's in config/deploy.php

### PR DESCRIPTION
**Pull request by xel1045**
For example you can modify the base Envoy.blade.php to something like this:

```
@setup
    $configFile = 'config/deploy.php';
@endsetup

@include('vendor/exolnet/laravel-envoy/init.php')

```

### CODE REVIEW

**Comment by xel1045** [comment]
Oups! Sorry! I've fix it!

**Comment by tomzx** [comment]
I may have a suggestion, although I'm not sure if it's a good one. We could set a list of locations to look for a `deploy.php` file, and the first that matches would be the one used. This way, we could have a solution that can work for both L4 and L5.

What do you think?

**Comment by xel1045** [comment]
On the long term, I think we should be the less framework agnostic.

**Comment by xel1045** [comment]
Oups... My other change was append! How could I manage my local repo to have multiple PR in parallel?

**Comment by tomzx** [comment]
You'd have to do the change in a separate branch.

**Comment by tomzx** [comment]
I assume you meant "more" framework agnostic? If that is the case, then "laravel-envoy" is going to be a bad project name in the near future :smile:.

**Comment by xel1045** [comment]
Yeah! I know that laravel-envoy would be a bad project name. Maybe we should change it soon.

**Pull request closed without merging**
