### PR TITLE
Feature/improve test coverage

### PR DESCRIPTION
**Pull request by ChristopheTremblay**
Improved test coverage from 8-% files, 42% lines to 100% files, 69% lines

### CODE REVIEW

**Comment by ChristopheTremblay** [comment]
Is there a way to make a connection to the Server::$url, or it is alway gonna try to call localhost:{a certain port} ?
The test will pass on local but break on the CI
1) Exolnet\Envoy\Tests\Unit\SlackTest::testSend
GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to 127.0.0.1 port 8126: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:8126/guzzle-server/responses

**Comment by xel1045** [comment]
Like you did in `laravel-image`, you can extract the `new Client` into a method. Then, you should be able to test the `send` method.

**Comment by ChristopheTremblay** [comment]
Like I did in laravel-image, I refactored the SLack::send method and extracted the creation of a new client inside a protected method Slack::makeClient. I was then able to mock this method and return a client created with a mockHandler.

The build is now green with a coverage of 100% files, 81% lines

**Comment by xel1045** [comment]
Everything looks good!

**Pull request merged**
